import "@/../styles/globals.css";
import Head from "next/head";
import Script from "next/script";
import Layout from "@/components/Layout";

const cdns = [
  "https://unpkg.com/react@17.0.2/umd/react.production.min.js",
  "https://unpkg.com/react-dom@17.0.2/umd/react-dom.production.min.js",
  'https://unpkg.com/moment@2.29.3/moment.js',
  'https://unpkg.com/less@4.1.2/dist/less.js',
  'https://unpkg.com/antd@4.19.5/dist/antd.min.js',
  'https://unpkg.com/axios@0.26.1/dist/axios.min.js'
];
const links = ["https://unpkg.com/antd@4.19.5/dist/antd.min.css"];

function MyApp({ Component, pageProps }) {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        {links.map((link) => (
          <link key={link} rel="stylesheet" href={link}></link>
        ))}
        {cdns.map((cdn) => (
          // eslint-disable-next-line @next/next/no-sync-scripts
          <script key={cdn} src={cdn}></script>
        ))}
      </Head>
      {/* {cdns.map((cdn) => (
        <Script key={cdn} src={cdn}></Script>
      ))} */}
      <Layout pageProps={pageProps}>
        <Component {...pageProps} />
      </Layout>
    </div>
  );
}

export default MyApp;
